### ISSUE TITLE
Missing Database from book

### ISSUE THREAD

**Issue by pputman12** [PacktPublishing/Learn-PostgreSQL#7]
Hello, in section 2, chapter on Basic Statements:

![image](https://user-images.githubusercontent.com/840282/130699964-e1a364a6-ad39-4676-a7b6-f453abd49fc7.png)

It says to make the db here, then right under it shows this:

![image](https://user-images.githubusercontent.com/840282/130699990-523f26f0-119f-47a0-8705-a617356830de.png)

So there's already a database created, and it uses this as an example to follow along from later, but there is no information in the db you create, so not sure where that came from.  Is there an additional sql statement to create this database with all the information?

**Comment by fluca1978** [comment]
Thanks for reporting this. I do agree that the writing in the chapter is not really clear about how to go from "no database at all" to "forumdb and its tables". We will fix that into the next version of the book. In the meantine I added a short section on the repository README.md that explains how to create the `forumdb` database. See <https://github.com/PacktPublishing/Learn-PostgreSQL#creating-the-example-database>, and if you believe this is enough clear please close the issue, or report back any improvement you can suggest.

**Comment by pputman12** [comment]
Thank you so much, this is more than enough, and  it really seems like a great book so far, I'm going to close this issue now.
