### ISSUE TITLE
Demo database 1000 users 5000 posts per user

### ISSUE THREAD

**Issue by pluraltouch** [PacktPublishing/Learn-PostgreSQL#8]
In chapter 13 the book states:

"In our demo database, there are 1,000 users (authors), each with 5,000
posts. The posts table requires around 480 megabytes of disk space."

Question:  
How can we create this amount of data, to allow demonstrate the execution plans and analyze statements? 
The setup seems to insert only a few rows. Is there anywhere a script to create the chapter prerequsites?

**Comment by fluca1978** [comment]
Good issue. 
You can generate the specified amount of data with something like:


```
INSERT INTO users( username, gecos, email )
SELECT 'user-' || v, 'Automatically generated user #' || v, 'author'|| v || '@learn-postgresql.org'
FROM generate_series( 1, 1000 ) v;


INSERT INTO posts( title, content, author, category, editable )
SELECT 'Thread-' || v, 'A question here for thread ' || v, a.pk, v % 3 + 1, case v % 2 when 0 then true else false end
FROM generate_series( 1, 5000 ) v, users a;
```

and you can check the amount of generated data with something like:

```
select a.username, count( p.pk )
from users a join posts p on p.author = a.pk 
group by a.username;

select pg_size_pretty( pg_table_size( 'posts' ) );
```


Please note that the above set of commands could create a table `posts` with around `1.2 GB` in size, if you want to stick near `400 MB` remove the content column, such as in

```
INSERT INTO posts( title,  author, category, editable )
SELECT 'Thread-' || v,  a.pk, v % 3 + 1, case v % 2 when 0 then true else false end
FROM generate_series( 1, 5000 ) v, users a;
```

**Comment by pluraltouch** [comment]
Hi Luca,

Many thx for your supports. After some progress in Postgres (thx to your book) I've managed to create similar solution.

Best Regards.
pluraltouch
